### ISSUE TITLE
Cannot create more than 1 shop

### ISSUE THREAD

**Issue by creative-ae** [reactioncommerce/reaction-platform#173]
## Issue Description
Creating a new shop from the admin dashboard fails with error: **Form "onSubmit" function error: Error: GraphQL error: There may be only one primary shop**

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. login to admin page
2. create first shop (this works normal)
3. try to create another shop
4. getting error  **Form "onSubmit" function error: Error: GraphQL error: There may be only one primary shop**

## Possible Solution
Graphql issue 

### Versions
3.11.1

**Comment by nigeltiany** [comment]
Hit this as well.
Found the issue and the princess is in another castle

https://github.com/reactioncommerce/api-plugin-shops/blob/7c356ef82756835abb23273a48bc4c41df2009ea/src/mutations/createShop.js#L91

It will always default to a primary shop when an option is not passed.
A proper fix would be to include a selector for the type of shop someone is creating. I haven't seen the documentation on the kinds of shops available. Looking at the code, there is ```merchant``` and ```primary```.

I will fork the plugin and set the default to ```merchant``` as a lazy fix since I already have primary shop.

**Comment by nigeltiany** [comment]
I eventually used another workaround.
go to the reaction-admin repository

https://github.com/reactioncommerce/reaction-admin/blob/784927a52c94b02438d0b4dac8884fa0d4485203/imports/plugins/core/dashboard/client/containers/CreateShopForm.js#L29

add this code before line 29
```js
input["type"] = "merchant"; // <- This specific line ...
const { data } = await createShop({
```

**Comment by MohanNarayana** [comment]
Fixed in [this PR](https://github.com/reactioncommerce/api-plugin-shops/pull/21)
