### ISSUE TITLE
Create a guide for release process

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-platform#204]
There is currently no documentation on how to do a release.

**Comment by birender-s** [comment]
@Akarshit, nice to see 4.0 release, congrats to the whole team !  It would be very helpful to have documentation and recorded session on setting up project (preferably on a Ubuntu VM on Azure/AWS/GCP) and demonstrate working of various basic features (login, create account, add product...). I've struggled a lot setting up project due to lack of precise steps/troubleshooting info and hope same for many fellow developers.
