### ISSUE TITLE
Make `make` command more resilient to misconfigured directory

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-platform#51]
## Issue Description
If any subdirectory underneath the parent doesn't have a `Dockerfile` the make command errors out and doesn't continue.

## Steps to Reproduce
1. Set up platform
1. Add a subdirectory without a Dockerfile
1. run `make`
1. Observe error
```
ERROR: Cannot locate specified Dockerfile: Dockerfile
make: *** [start-reaction-etl-shippable-inventory] Error 1
```

## Possible Solution
Possible check for existence of the file and skip whatever step is trying to use this file

### Versions
`release-2.0.0-rc.9`

**Comment by ticean** [comment]
This isn't an error. A `docker build` is only attempted on projects that are included in the `config.mk` or `config.local.mk`. Those projects should be top-level services. Errors on Docker build shouldn't be skipped because that would indicate a serious problem. Make tasks should fail and explicitly show the error so it can be fixed.

From your example, I see you're including plugins in the list, which you shouldn't do. Plugins aren't services. They're sub components of the `reaction` service. Include them into `reaction` by mechanisms of your choice (ie submodules, or scripting). _Reaction should offer a standard way of doing that dependency management, but that's a separate topic._

You can always checkout any projects you'd like into the platform directory for convenience. Just don't include them in your `config.local.mk` project list.

**Comment by zenweasel** [comment]
Incorrect, that is not a plugin

**Comment by ticean** [comment]
Does the project start a long-running process on your local machine?

**Comment by zenweasel** [comment]
Nevermind, I see what you are saying. Closing
