### ISSUE TITLE
Idea: Add checkout command

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-platform#9]
There could be a simple file mapping one "platform" version to git tags for each repo. For example, `make checkout 2.0` might git checkout `2.0` tag of Reaction repo, `1.0` tag of starter kit, and `1.0` tag of hydra. Otherwise it gets tricky making sure you have all of your service versions aligned before you `make start`.

**Comment by aldeed** [comment]
cc @ticean

**Comment by aldeed** [comment]
A related issue is that `make` doesn't prompt you for which branch of each repo to check out. It just starts cloning and building, which is a waste of time of you're going to have to stop the service, checkout a different release, and rebuild it after it's done.

**Comment by ticean** [comment]
Some thoughts on how this could work:

The Makefile currently defines [an array of projects](https://github.com/reactioncommerce/reaction-platform/blob/3d5cd46a4b187fe2d3f9aaa1d51df5684c17bec7/Makefile#L26-L32). Most of the targets are created by some metaprogramming that iterate over the list. There are some global assumptions currently made in the file that need to be addressed.

1. That all projects are in the `reactioncommerce` Github organization.
2. That the `master` branch of each project will be used.

#### Proposed Solution

Declare data in a way that does not make these assumptions.

1. If possible, use a multi-dimensional array to declare `($org/$project $git_ref)`. Or, find another workaround to get the data points into the targets.
2. Modify the [cloning targets](https://github.com/reactioncommerce/reaction-platform/blob/3d5cd46a4b187fe2d3f9aaa1d51df5684c17bec7/Makefile#L139-L143) so that the organization isn't hardcoded.
3. Add a checkout step that would checkout to a git ref after clone.
4. Modify the existing target meta templates to accept and use the various parts from the new data structure.

**Comment by focusaurus** [comment]
So one thing I figured out as a note to self is we could in theory have one variable be a list of repo URLs and parse out the repo directory names as another variable like this:

```
REACTION_PROJECT_URLS=git@github.com/reactioncommerce/reaction-hydra.git\#master \
		  git@github.com/reactioncommerce/reaction.git\#master \
		  git@github.com/reactioncommerce/reaction-next-starterkit.git\#master

# Yeah, there's a bunch of make and shell and sed escaping here. Sorry.
REACTION_PROJECTS2=$(foreach rp,$(REACTION_PROJECT_URLS),$(shell basename $(rp) | cut -d \\\# -f 1 | sed 's/\.git$$//'))
```

That does seem to work BUT it uses unix stuff so is that a dealbreaker for windows installs?

**Comment by aldeed** [comment]
Make doesn't work on Windows anyway, does it?

@ticean I like your solution, and it should be keyed by version as well, i.e., platform version X = these 5 repos w/ checkout tags. In my perfect world, this would be defined in a separate file, ideally JSON or YAML. Not sure how easy it is to parse those in Make.

And on the subject of Make... I still think it would be better to find a different task runner that will work on any OS. Otherwise we are saying, "yeah we still support Windows, just use Docker" and "you should really use platform to bootstrap everything" but those statements are incompatible.

**Comment by focusaurus** [comment]
OK I have a WIP pull request for adding checkout capabilities and a very simple manifest without much new code. Apologies about how inscrutable the make metaprogramming and escaping makes things, but I think it does what's necessary here.

More broadly we should figure out our Windows story. As it is it's using GNU make which I believe doesn't directly work on Windows but there seem to be some cygwin-style ports. Dunno. But we're also using a handful of POSIX things like awk, xargs, cut, grep, etc so we'd at least have to require POSIX tools as a prereq. 

I'd be OK with scripting things as node scripts or going all-docker if we start to run into limitations of only relying on basic text utilities.

**Comment by focusaurus** [comment]
@aldeed revisiting your initial description of this feature, I guess we could add a data file for that. If we could use `jq` the data munging would be a lot less fidgety. Maybe JSON files like `releases/2.0.json`

```json
{
  "subProjects": [
    {"name": "reaction-hydra", "gitUrl": "git@github.com:reactioncommerce/reaction-hydra.git", "tag": "2.0"},
    {"name": "reaction-next-starterkit", "gitUrl": "git@github.com:reactioncommerce/reaction-next-starterkit.git", "tag": "1.7"}
  ]
}
```

**Comment by focusaurus** [comment]
Note to self: `jq -r ".\"2.0\".subProjects[].gitUrl" < releases.json`

**Comment by focusaurus** [comment]
OK to keep scope well-tracked, I'm going to file a separate issue to discuss the toolchain choice. Let's keep this issue about a checkout command specifically. We may decide not to implement on top of the existing toolchain and Makefile.
