### ISSUE TITLE
make: Makefile 183: build-reaction-hydra error 127

### ISSUE THREAD

**Issue by tccack** [reactioncommerce/reaction-platform#93]
Hi all... trying to install reaction platform on rpi4. Raspbian/Debian/Buster
Have followed the process instructions without too many issues.
have done the ssh key stuff and the prerequisites etc.
Cloned fine and directory exists etc

I do note that there is a statement that docker-compose "not found". The file is definitely there however (though if its valid I do not know). The contents are "Not Found"
Note that this was a second attempt at installing hence the "already exists" messages. These did not occur during the first attempt. There appeared to be no issues until the final error line, which persists.

pi@raspberrypi:~/reaction-platform $ make
Error response from daemon: network with name auth.reaction.localhost already exists
Error response from daemon: network with name api.reaction.localhost already exists
Error response from daemon: network with name streams.reaction.localhost already exists
Running pre-build hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
/usr/local/bin/docker-compose: 1: /usr/local/bin/docker-compose: Not: not found
make: *** [Makefile:183: build-reaction-hydra] Error 127

**Comment by spencern** [comment]
I've not experimented with installing Reaction on a raspberry pi.
Have you run docker-compose on your rpi4 for other projects? This error seems to be telling you that the make script can't access docker-compose as it expects.

**Comment by aldeed** [comment]
@tccack It seems the `docker-compose` _command_ is not found, rather than the file. On a lightweight Linux distro you'll definitely need to install both Docker and Docker Compose separately, and they may have their own program dependencies that won't be pre-installed on Raspbian. See:

- https://hub.docker.com/editions/community/docker-ce-server-debian
- https://docs.docker.com/compose/install/

Since the Reaction projects run in lightweight (Alpine) Linux Docker images anyway, you most likely could run all the services directly on the rPi without Docker, but it will be some work for you to figure out all of the proper environment variables and networking to get them all talking with each other. This isn't currently something we can provide free support for or guarantee in any way, but sounds like a fun experiment!

**Comment by tccack** [comment]
Both docker and compose seemed to install ok. I have installed portainer also which starts and runs fine. I think I'll wipe the pi4 and start again and see if it can be run directly on the pi.
(not sure this is in the category of fun project but I'm keen to give the reaction suite a go)
Docker runs really well on my pi3b but pi4 doesnt seem to be as straight forward.
I'll close this off and start another if issues arise from trying the other way.
